---
title: "Covid-19: Brasil"
author: "Vinícius Barbosa Godinho"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: menu
    
---

```{r setup, include=FALSE}


con <- gzcon(url(paste("https://data.brasil.io/dataset/covid19/caso_full.csv.gz", sep=",")))
txt <- readLines(con)
dados <- read.csv(textConnection(txt))


library("dplyr")
library("tidyr")
library("lubridate")
library("ggplot2")
require('tikzDevice')
library("devtools")
library(plotly)
library("flexdashboard")
library("sf")  
library("tmap")
library("tmaptools")
library("rgdal")
library("leaflet")





colnames(dados)[8] <-'confirmed'
colnames(dados)[12] <-'deaths'
colnames(dados)[9] <- 'confirmed_per_100k'




###Brasil


dados_brasil_total <- dados %>%
  filter(place_type=="state") %>%
  arrange(date) %>%
  mutate(deaths_per_100k= (100000*deaths)/estimated_population_2019) 




dados_brasil <- group_by(dados_brasil_total,date)%>%summarise(confirmed=sum(confirmed), deaths=sum(deaths),new_confirmed=sum(new_confirmed), new_deaths=sum(new_deaths),confirmed_per_100k=sum(confirmed_per_100k), deaths_per_100k=sum(deaths_per_100k))



dados_brasil$date <- as.Date(dados_brasil$date)


dados_brasil <- dados_brasil%>%
  mutate(ma7_confirmed = stats::filter(dados_brasil$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_brasil$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))



##gráficos
###Acumulado

brasil_casos_total <- data.frame(casos=c(rep("Confirmados",nrow(dados_brasil)),rep("Obitos",nrow(dados_brasil))), data = rep(dados_brasil$date,2), total = c(dados_brasil$confirmed,dados_brasil$deaths))



####Log acumulados


brasil_casos_log <- data.frame(casos=c(rep("Confirmados",nrow(dados_brasil)),rep("Obitos",nrow(dados_brasil))), data = rep(dados_brasil$date,2), total = c(log(dados_brasil$confirmed),log(dados_brasil$deaths)))



###Por 100 mil habitante

brasil_casos_per_100k <- data.frame(casos=c(rep("Confirmados",nrow(dados_brasil)),rep("Obitos",nrow(dados_brasil))), data = rep(dados_brasil$date,2), total = c(dados_brasil$confirmed_per_100k,dados_brasil$deaths_per_100k))


###média móvel 7 dias

####casos

dados_brasil$ma7_confirmed <- as.numeric(dados_brasil$ma7_confirmed)


##óbitos

dados_brasil$ma7_deaths <- as.numeric(dados_brasil$ma7_deaths)





###Centro Oeste
#DF, GO, MT, MS

dados_co <- dados %>%
  filter(place_type == "state", state=="DF" |state=="GO" |state=="MT" |state=="MS") %>%
  arrange(date) %>%
  mutate(deaths_per_100k= (100000*deaths)/estimated_population_2019) 



dados_co$date <- as.Date(dados_co$date)


###Média móvel
#df
dados_df <- dados %>%
  filter(place_type=="state", state =="DF") 


dados_df <- dados_df%>%
  mutate(ma7_confirmed = stats::filter(dados_df$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_df$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))



#goias
dados_go <- dados %>%
  filter(place_type=="state", state =="GO") 


dados_go <- dados_go%>%
  mutate(ma7_confirmed = stats::filter(dados_go$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_go$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#mt
dados_mt <- dados %>%
  filter(place_type=="state", state =="MT") 


dados_mt <- dados_mt%>%
  mutate(ma7_confirmed = stats::filter(dados_mt$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_mt$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))


#ms


dados_ms <- dados %>%
  filter(place_type=="state", state =="MS") 


dados_ms <- dados_ms%>%
  mutate(ma7_confirmed = stats::filter(dados_ms$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_ms$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))




dados_co_full<- rbind.data.frame(dados_df,dados_go,dados_mt,dados_ms)

dados_co_full$date <- as.Date(dados_co_full$date)




###Sudeste
#ES, MG, RJ, SP

dados_sd <- dados %>%
  filter(place_type == "state", state=="ES" |state=="MG" |state=="RJ" |state=="SP") %>%
  arrange(date) %>%
  mutate(deaths_per_100k= (100000*deaths)/estimated_population_2019) 



dados_sd$date <- as.Date(dados_sd$date)


###Média móvel
#ES
dados_es <- dados %>%
  filter(place_type=="state", state =="ES") 


dados_es <- dados_es%>%
  mutate(ma7_confirmed = stats::filter(dados_es$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_es$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))



#mg
dados_mg <- dados %>%
  filter(place_type=="state", state =="MG") 


dados_mg <- dados_mg%>%
  mutate(ma7_confirmed = stats::filter(dados_mg$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_mg$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#rj
dados_rj <- dados %>%
  filter(place_type=="state", state =="RJ") 


dados_rj <- dados_rj%>%
  mutate(ma7_confirmed = stats::filter(dados_rj$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_rj$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))


#sp


dados_sp <- dados %>%
  filter(place_type=="state", state =="SP") 


dados_sp <- dados_sp%>%
  mutate(ma7_confirmed = stats::filter(dados_sp$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_sp$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))




dados_sd_full<- rbind.data.frame(dados_es,dados_mg,dados_rj,dados_sp)

dados_sd_full$date <- as.Date(dados_sd_full$date)





###Sul
#PR, RS, SC

dados_su <- dados %>%
  filter(place_type == "state", state=="PR" |state=="RS" |state=="SC") %>%
  arrange(date) %>%
  mutate(deaths_per_100k= (100000*deaths)/estimated_population_2019) 



dados_su$date <- as.Date(dados_su$date)


###Média móvel
#PR
dados_pr <- dados %>%
  filter(place_type=="state", state =="PR") 


dados_pr <- dados_pr%>%
  mutate(ma7_confirmed = stats::filter(dados_pr$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_pr$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))



#mg
dados_rs <- dados %>%
  filter(place_type=="state", state =="RS") 


dados_rs <- dados_rs%>%
  mutate(ma7_confirmed = stats::filter(dados_rs$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_rs$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#SC
dados_sc <- dados %>%
  filter(place_type=="state", state =="SC") 


dados_sc <- dados_sc%>%
  mutate(ma7_confirmed = stats::filter(dados_sc$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_sc$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))



dados_su_full<- rbind.data.frame(dados_pr,dados_rs,dados_sc)

dados_su_full$date <- as.Date(dados_su_full$date)


###Nordeste

###Sul
#AL,BA,CE,PB,PI,PE,MA,RN,SE

dados_ne <- dados %>%
  filter(place_type == "state", state=="AL" |state=="BA" |state=="CE"|state=="PB"|state=="PE"|state=="PI"|state=="MA"|state=="RN"|state=="SE") %>%
  arrange(date) %>%
  mutate(deaths_per_100k= (100000*deaths)/estimated_population_2019) 



dados_ne$date <- as.Date(dados_ne$date)


###Média móvel
#AL
dados_al <- dados %>%
  filter(place_type=="state", state =="AL") 


dados_al <- dados_al%>%
  mutate(ma7_confirmed = stats::filter(dados_al$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_al$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))



#ba
dados_ba <- dados %>%
  filter(place_type=="state", state =="BA") 


dados_ba <- dados_ba%>%
  mutate(ma7_confirmed = stats::filter(dados_ba$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_ba$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#CE
dados_ce <- dados %>%
  filter(place_type=="state", state =="CE") 


dados_ce <- dados_ce%>%
  mutate(ma7_confirmed = stats::filter(dados_ce$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_ce$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))


#PB
dados_pb <- dados %>%
  filter(place_type=="state", state =="PB") 


dados_pb <- dados_pb%>%
  mutate(ma7_confirmed = stats::filter(dados_pb$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_pb$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))
#PE
dados_pe <- dados %>%
  filter(place_type=="state", state =="PE") 


dados_pe <- dados_pe%>%
  mutate(ma7_confirmed = stats::filter(dados_pe$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_pe$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))
#PI
dados_pi <- dados %>%
  filter(place_type=="state", state =="PI") 


dados_pi <- dados_pi%>%
  mutate(ma7_confirmed = stats::filter(dados_pi$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_pi$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))
#MA
dados_ma <- dados %>%
  filter(place_type=="state", state =="MA") 


dados_ma <- dados_ma%>%
  mutate(ma7_confirmed = stats::filter(dados_ma$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_ma$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))
#RN
dados_rn <- dados %>%
  filter(place_type=="state", state =="RN") 


dados_rn <- dados_rn%>%
  mutate(ma7_confirmed = stats::filter(dados_rn$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_rn$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#SE
dados_se <- dados %>%
  filter(place_type=="state", state =="SE") 


dados_se <- dados_se%>%
  mutate(ma7_confirmed = stats::filter(dados_se$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_se$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))




dados_ne_full<- rbind.data.frame(dados_al,dados_ba,dados_ce,dados_pb,dados_pe,dados_pi,dados_ma,dados_rn,dados_se)

dados_ne_full$date <- as.Date(dados_ne_full$date)




###Norte


#Acre, Amapá, Amazonas, Pará, Rondônia, Roraima e Tocantins


dados_no <- dados %>%
  filter(place_type == "state", state=="AC" |state=="AP" |state=="AM"|state=="PA"|state=="RO"|state=="RR"|state=="TO") %>%
  arrange(date) %>%
  mutate(deaths_per_100k= (100000*deaths)/estimated_population_2019) 



dados_no$date <- as.Date(dados_no$date)



###Média móvel
#AC
dados_ac <- dados %>%
  filter(place_type=="state", state =="AC") 


dados_ac <- dados_ac%>%
  mutate(ma7_confirmed = stats::filter(dados_ac$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_ac$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))



#ap
dados_ap <- dados %>%
  filter(place_type=="state", state =="AP") 


dados_ap <- dados_ap%>%
  mutate(ma7_confirmed = stats::filter(dados_ap$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_ap$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#AM
dados_am <- dados %>%
  filter(place_type=="state", state =="AM") 


dados_am <- dados_am%>%
  mutate(ma7_confirmed = stats::filter(dados_am$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_am$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))


#PA
dados_pa <- dados %>%
  filter(place_type=="state", state =="PA") 


dados_pa <- dados_pa%>%
  mutate(ma7_confirmed = stats::filter(dados_pa$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_pa$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#PE
dados_ro <- dados %>%
  filter(place_type=="state", state =="RO") 


dados_ro <- dados_ro%>%
  mutate(ma7_confirmed = stats::filter(dados_ro$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_ro$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))
#RR
dados_rr <- dados %>%
  filter(place_type=="state", state =="RR") 


dados_rr <- dados_rr%>%
  mutate(ma7_confirmed = stats::filter(dados_rr$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_rr$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))
#TO
dados_to <- dados %>%
  filter(place_type=="state", state =="TO") 


dados_to <- dados_to%>%
  mutate(ma7_confirmed = stats::filter(dados_to$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_to$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))


dados_no_full<- rbind.data.frame(dados_ac,dados_ap,dados_am,dados_pa,dados_ro,dados_rr,dados_to)

dados_no_full$date <- as.Date(dados_no_full$date)




dados_full<- rbind.data.frame(dados_sd_full,dados_su_full,dados_co_full,dados_no_full,dados_ne_full)

dados_full$date <- as.Date(dados_full$date)





dados_full <- dados_full 
###Agrupar regiões


##Brasil

df_brasil <- dados_brasil %>%
  mutate(state= "Brasil") %>%
  select(date,confirmed,deaths,new_confirmed,new_deaths,ma7_confirmed,ma7_deaths,state)


##Centro-Oeste

df_co <- group_by(dados_co_full,date)%>%
summarise(confirmed=sum(confirmed), deaths=sum(deaths),new_confirmed=sum(new_confirmed), new_deaths=sum(new_deaths))

df_co <- df_co%>%
  mutate(ma7_confirmed = stats::filter(df_co$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(df_co$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(state= "Centro-Oeste")

##Nordeste

df_ne <- group_by(dados_ne_full,date)%>%
  summarise(confirmed=sum(confirmed), deaths=sum(deaths),new_confirmed=sum(new_confirmed), new_deaths=sum(new_deaths))

df_ne <- df_ne%>%
  mutate(ma7_confirmed = stats::filter(df_ne$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(df_ne$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(state= "Nordeste")



##Norte

df_no <- group_by(dados_no_full,date)%>%
  summarise(confirmed=sum(confirmed), deaths=sum(deaths),new_confirmed=sum(new_confirmed), new_deaths=sum(new_deaths))

df_no <- df_no%>%
  mutate(ma7_confirmed = stats::filter(df_no$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(df_no$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(state= "Norte")


##Sudeste

df_sd <- group_by(dados_sd_full,date)%>%
  summarise(confirmed=sum(confirmed), deaths=sum(deaths),new_confirmed=sum(new_confirmed), new_deaths=sum(new_deaths))

df_sd <- df_sd%>%
  mutate(ma7_confirmed = stats::filter(df_sd$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(df_sd$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(state= "Sudeste")

##Sul

df_su <- group_by(dados_su_full,date)%>%
  summarise(confirmed=sum(confirmed), deaths=sum(deaths),new_confirmed=sum(new_confirmed), new_deaths=sum(new_deaths))

df_su <- df_su%>%
  mutate(ma7_confirmed = stats::filter(df_su$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(df_su$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(state= "Sul")



df_full_regiao<- rbind.data.frame(df_co,df_ne,df_no,df_sd,df_su)


df_full_regiao <- df_full_regiao 


####capitais


#Porto Velho		 

dados_porto_velho <- dados %>%
  filter(place_type=="city",  city_ibge_code=="1100205") 


dados_porto_velho <- dados_porto_velho%>%
  mutate(ma7_confirmed = stats::filter(dados_porto_velho$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_porto_velho$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Manaus		 

dados_manaus <- dados %>%
  filter(place_type=="city",  city_ibge_code=="1302603") 


dados_manaus <- dados_manaus%>%
  mutate(ma7_confirmed = stats::filter(dados_manaus$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_manaus$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Rio Branco		 

dados_rio_branco <- dados %>%
  filter(place_type=="city",  city_ibge_code=="1200401") 


dados_rio_branco <- dados_rio_branco%>%
  mutate(ma7_confirmed = stats::filter(dados_rio_branco$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_rio_branco$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Campo Grande		 

dados_campo_grande <- dados %>%
  filter(place_type=="city",  city_ibge_code=="5002704") 


dados_campo_grande <- dados_campo_grande%>%
  mutate(ma7_confirmed = stats::filter(dados_campo_grande$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_campo_grande$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Macapá		 

dados_macapa <- dados %>%
  filter(place_type=="city",  city_ibge_code=="1600303") 


dados_macapa <- dados_macapa%>%
  mutate(ma7_confirmed = stats::filter(dados_macapa$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_macapa$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Brasília		 

dados_brasilia <- dados %>%
  filter(place_type=="city",  city_ibge_code=="5300108") 


dados_brasilia <- dados_brasilia%>%
  mutate(ma7_confirmed = stats::filter(dados_brasilia$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_brasilia$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Boa Vista		

dados_boa_vista <- dados %>%
  filter(place_type=="city",  city_ibge_code=="1400100") 


dados_boa_vista <- dados_boa_vista%>%
  mutate(ma7_confirmed = stats::filter(dados_boa_vista$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_boa_vista$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Cuiabá		 

dados_cuiaba <- dados %>%
  filter(place_type=="city",  city_ibge_code=="5103403") 


dados_cuiaba <- dados_cuiaba%>%
  mutate(ma7_confirmed = stats::filter(dados_cuiaba$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_cuiaba$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Palmas		 

dados_palmas <- dados %>%
  filter(place_type=="city",  city_ibge_code=="1721000") 


dados_palmas <- dados_palmas%>%
  mutate(ma7_confirmed = stats::filter(dados_palmas$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_palmas$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Teresina		

dados_teresina <- dados %>%
  filter(place_type=="city",  city_ibge_code=="2211001") 


dados_teresina <- dados_teresina%>%
  mutate(ma7_confirmed = stats::filter(dados_teresina$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_teresina$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#São Paulo		

dados_sao_paulo <- dados %>%
  filter(place_type=="city",  city_ibge_code=="3550308") 


dados_sao_paulo <- dados_sao_paulo%>%
  mutate(ma7_confirmed = stats::filter(dados_sao_paulo$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_sao_paulo$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Rio de Janeiro		

dados_rio_de_janeiro <- dados %>%
  filter(place_type=="city",  city_ibge_code=="3304557") 


dados_rio_de_janeiro <- dados_rio_de_janeiro%>%
  mutate(ma7_confirmed = stats::filter(dados_rio_de_janeiro$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_rio_de_janeiro$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Belém		

dados_belem <- dados %>%
  filter(place_type=="city",  city_ibge_code=="1501402") 


dados_belem <- dados_belem%>%
  mutate(ma7_confirmed = stats::filter(dados_belem$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_belem$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#São Luís	

dados_sao_luis <- dados %>%
  filter(place_type=="city",  city_ibge_code=="2111300") 


dados_sao_luis <- dados_sao_luis%>%
  mutate(ma7_confirmed = stats::filter(dados_sao_luis$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_sao_luis$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Goiânia		 

dados_goiania <- dados %>%
  filter(place_type=="city",  city_ibge_code=="5208707") 


dados_goiania <- dados_goiania%>%
  mutate(ma7_confirmed = stats::filter(dados_goiania$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_goiania$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Salvador		

dados_salvador <- dados %>%
  filter(place_type=="city",  city_ibge_code=="2927408") 


dados_salvador <- dados_salvador%>%
  mutate(ma7_confirmed = stats::filter(dados_salvador$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_salvador$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Maceió		 

dados_maceio <- dados %>%
  filter(place_type=="city",  city_ibge_code=="2704302") 


dados_maceio <- dados_maceio%>%
  mutate(ma7_confirmed = stats::filter(dados_maceio$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_maceio$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Porto Alegre		

dados_porto_alegre <- dados %>%
  filter(place_type=="city",  city_ibge_code=="4314902") 


dados_porto_alegre <- dados_porto_alegre%>%
  mutate(ma7_confirmed = stats::filter(dados_porto_alegre$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_porto_alegre$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Curitiba		

dados_curitiba <- dados %>%
  filter(place_type=="city",  city_ibge_code=="4106902") 


dados_curitiba <- dados_curitiba%>%
  mutate(ma7_confirmed = stats::filter(dados_curitiba$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_curitiba$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Florianópolis		

dados_florianopolis <- dados %>%
  filter(place_type=="city",  city_ibge_code=="4205407") 


dados_florianopolis <- dados_florianopolis%>%
  mutate(ma7_confirmed = stats::filter(dados_florianopolis$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_florianopolis$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Belo Horizonte		

dados_belo_horizonte <- dados %>%
  filter(place_type=="city",  city_ibge_code=="3106200") 


dados_belo_horizonte <- dados_belo_horizonte%>%
  mutate(ma7_confirmed = stats::filter(dados_belo_horizonte$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_belo_horizonte$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Fortaleza		

dados_fortaleza <- dados %>%
  filter(place_type=="city",  city_ibge_code=="2304400") 


dados_fortaleza <- dados_fortaleza%>%
  mutate(ma7_confirmed = stats::filter(dados_fortaleza$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_fortaleza$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Recife		 

dados_recife <- dados %>%
  filter(place_type=="city",  city_ibge_code=="2611606") 


dados_recife <- dados_recife%>%
  mutate(ma7_confirmed = stats::filter(dados_recife$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_recife$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#João Pessoa		 

dados_joao_pessoa <- dados %>%
  filter(place_type=="city",  city_ibge_code=="2507507") 


dados_joao_pessoa <- dados_joao_pessoa%>%
  mutate(ma7_confirmed = stats::filter(dados_joao_pessoa$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_joao_pessoa$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Aracaju		 

dados_aracaju <- dados %>%
  filter(place_type=="city",  city_ibge_code=="2800308") 


dados_aracaju <- dados_aracaju%>%
  mutate(ma7_confirmed = stats::filter(dados_aracaju$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_aracaju$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))

#Natal		 

dados_natal <- dados %>%
  filter(place_type=="city",  city_ibge_code=="2408102") 


dados_natal <- dados_natal%>%
  mutate(ma7_confirmed = stats::filter(dados_natal$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_natal$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))


#Vitória	


dados_vitoria <- dados %>%
  filter(place_type=="city",  city_ibge_code=="3205309") 


dados_vitoria <- dados_vitoria%>%
  mutate(ma7_confirmed = stats::filter(dados_vitoria$new_confirmed, filter=rep(1/7, 7), method="convolution", sides=1, circular=F)) %>%
  mutate(ma7_deaths = stats::filter(dados_vitoria$new_deaths, filter=rep(1/7, 7), method="convolution", sides=1, circular=F))


dados_capitais<- rbind.data.frame(dados_aracaju,dados_belem,dados_belo_horizonte,
                                       dados_boa_vista,dados_brasilia,dados_campo_grande,
                                       dados_cuiaba,dados_curitiba,dados_florianopolis,
                                       dados_fortaleza,dados_goiania,dados_joao_pessoa,
                                       dados_macapa,dados_maceio,dados_manaus,dados_natal,
                                       dados_palmas,dados_porto_alegre,dados_porto_velho,
                                       dados_recife,dados_rio_branco,dados_rio_de_janeiro,
                                       dados_salvador,dados_sao_luis,dados_sao_paulo,
                                       dados_teresina,dados_vitoria)
  




dados_capitais$date <- as.Date(dados_capitais$date)



```

Brasil
=======================================================================


Row
-------------------------------------

### Última Atualização

```{r}
valueBox(format(today(), "%d/%m/%Y"),
         color = "gray")
```


### Total de Casos

```{r}
valueBox(max(df_brasil$confirmed))
```

### Novos Casos

```{r}
valueBox(df_brasil$new_confirmed[nrow(df_brasil)])
```

### Total de Óbitos

```{r}
valueBox(max(df_brasil$deaths),
         color = "red")

```

### Novos Óbitos

```{r}
valueBox(df_brasil$new_deaths[nrow(df_brasil)],
         color = "red")
```

### Taxa de Letalidade (%)

```{r}
valueBox(gsub('\\.',',',round((max(df_brasil$deaths)/max(df_brasil$confirmed))*100,
         digits = 2)),
         color = "gray")
```


Row
-----------------------------------------------------------------------

### Média Móvel 7 dias: Novos Casos

```{r}



g1_brasil <- ggplot(df_brasil, aes(date, ma7_confirmed)) +geom_line(size=.8, color="darkblue")+
  xlab("Data") +
  ylab("") +
  scale_x_date(date_labels = "%d/%m")+
  theme(text = element_text(size=8) ,
        axis.text.x = element_text(angle = 45), 
        axis.title.x = element_text(size=8), 
        legend.text = element_text(size=5,hjust = 0) ,
        legend.position = "bottom",legend.title = element_blank(), 
        legend.key =element_blank(), panel.background = element_blank(), 
        panel.grid.minor = element_line(colour = "gray90"), 
        panel.grid.major = element_line(colour = "gray90"))



ggplotly(g1_brasil)%>% 
  layout(annotations = 
           list(x = 1, y = -0.08, text = "Dados:SES. Disponibilizado: https://data.brasil.io/. Elaborado: Vinicius Godinho.", 
                showarrow = F, xref='paper', yref='paper', 
                xanchor='right', yanchor='auto', xshift=0, yshift=0,
                font=list(size=8))
  )
  
  
```


### Média Móvel 7 dias: Novos Óbitos

```{r}

g2_brasil <- ggplot(df_brasil, aes(date, ma7_deaths)) +geom_line(size=.8, color="darkred")+
  xlab("Data") +
  ylab("") +
  scale_x_date(date_labels = "%d/%m")+
  theme(text = element_text(size=8) ,
        axis.text.x = element_text(angle = 45), 
        axis.title.x = element_text(size=8), 
        legend.text = element_text(size=5,hjust = 0) ,
        legend.position = "bottom",legend.title = element_blank(), 
        legend.key =element_blank(), panel.background = element_blank(), 
        panel.grid.minor = element_line(colour = "gray90"), 
        panel.grid.major = element_line(colour = "gray90"))



ggplotly(g2_brasil)%>% 
  layout(annotations = 
           list(x = 1, y = -0.08, text = "Dados:SES. Disponibilizado: https://data.brasil.io/. Elaborado: Vinicius Godinho.", 
                showarrow = F, xref='paper', yref='paper', 
                xanchor='right', yanchor='auto', xshift=0, yshift=0,
                font=list(size=8))
  )


```

Regiões
=======================================================================

Row
-----------------------------------------------------------------------

### Média Móvel 7 dias: Novos Casos

```{r}


g3_regiao <- ggplot(df_full_regiao, aes(date, ma7_confirmed, colour = state)) +geom_line(size=.8)  +
  xlab("Data") +
  ylab("") +
  scale_x_date(date_labels = "%d/%m")+
  theme(text = element_text(size=8) ,
        axis.text.x = element_text(angle = 45), 
        axis.title.x = element_text(size=8), 
        legend.text = element_text(size=5,hjust = 0) ,
        legend.position = "bottom",legend.title = element_blank(), 
        legend.key =element_blank(), panel.background = element_blank(), 
        panel.grid.minor = element_line(colour = "gray90"), 
        panel.grid.major = element_line(colour = "gray90"))


ggplotly(g3_regiao)%>% 
  layout(annotations = 
           list(x = 1, y = -0.08, text = "Dados:SES. Disponibilizado: https://data.brasil.io/. Elaborado: Vinicius Godinho.", 
                showarrow = F, xref='paper', yref='paper', 
                xanchor='right', yanchor='auto', xshift=0, yshift=0,
                font=list(size=8))
  )
  
  
```

### Média Móvel 7 dias: Novos Óbitos

```{r}



g4_regiao <- ggplot(df_full_regiao, aes(date, ma7_deaths, colour = state)) +geom_line(size=.8)  +
  xlab("Data") +
  ylab("") +
  scale_x_date(date_labels = "%d/%m")+
  theme(text = element_text(size=8) ,
        axis.text.x = element_text(angle = 45), 
        axis.title.x = element_text(size=8), 
        legend.text = element_text(size=5,hjust = 0) ,
        legend.position = "bottom",legend.title = element_blank(), 
        legend.key =element_blank(), panel.background = element_blank(), 
        panel.grid.minor = element_line(colour = "gray90"), 
        panel.grid.major = element_line(colour = "gray90"))






ggplotly(g4_regiao)%>% 
  layout(annotations = 
           list(x = 1, y = -0.08, text = "Dados:SES. Disponibilizado: https://data.brasil.io/. Elaborado: Vinicius Godinho.", 
                showarrow = F, xref='paper', yref='paper', 
                xanchor='right', yanchor='auto', xshift=0, yshift=0,
                font=list(size=8))
  )
  
```


Estados
=======================================================================

Row
-----------------------------------------------------------------------

### Média Móvel 7 dias: Novos Casos

```{r}


g3_full <- ggplot(dados_full, aes(date, ma7_confirmed, colour = state)) +geom_line(size=.8)  +
  xlab("Data") +
  ylab("") +
  scale_x_date(date_labels = "%d/%m")+
  theme(text = element_text(size=8) ,
        axis.text.x = element_text(angle = 45), 
        axis.title.x = element_text(size=8), 
        legend.text = element_text(size=5,hjust = 0) ,
        legend.position = "bottom",legend.title = element_blank(), 
        legend.key =element_blank(), panel.background = element_blank(), 
        panel.grid.minor = element_line(colour = "gray90"), 
        panel.grid.major = element_line(colour = "gray90"))



ggplotly(g3_full)%>% 
  layout(annotations = 
           list(x = 1, y = -0.08, text = "Dados:SES. Disponibilizado: https://data.brasil.io/. Elaborado: Vinicius Godinho.", 
                showarrow = F, xref='paper', yref='paper', 
                xanchor='right', yanchor='auto', xshift=0, yshift=0,
                font=list(size=8))
  )
  
  
```

### Média Móvel 7 dias: Novos Óbitos

```{r}



g4_full <- ggplot(dados_full, aes(date, ma7_deaths, colour = state)) +geom_line(size=.8)  +
  xlab("Data") +
  ylab("") +
  scale_x_date(date_labels = "%d/%m") +
  theme(text = element_text(size=8) ,
    
        axis.text.x = element_text(angle = 45), 
        axis.title.x = element_text(size=8), 
        legend.text = element_text(size=5,hjust = 0) ,
        legend.position = "bottom",legend.title = element_blank(), 
        legend.key =element_blank(), panel.background = element_blank(), 
        panel.grid.minor = element_line(colour = "gray90"), 
        panel.grid.major = element_line(colour = "gray90"))




ggplotly(g4_full)%>% 
  layout(annotations = 
           list(x = 1, y = -0.08, text = "Dados:SES. Disponibilizado: https://data.brasil.io/. Elaborado: Vinicius Godinho.", 
                showarrow = F, xref='paper', yref='paper', 
                xanchor='right', yanchor='auto', xshift=0, yshift=0,
                font=list(size=8))
  )
  
```



Capitais
=======================================================================

Row
-----------------------------------------------------------------------

### Média Móvel 7 dias: Novos Casos

```{r}


g1_capitais <- ggplot(dados_capitais, aes(date, ma7_confirmed, colour = city)) +geom_line(size=.8)  +
  xlab("Data") +
  ylab("") +
  scale_x_date(date_labels = "%d/%m")+
  theme(text = element_text(size=8) ,
        axis.text.x = element_text(angle = 45), 
        axis.title.x = element_text(size=8), 
        legend.text = element_text(size=5,hjust = 0) ,
        legend.position = "bottom",legend.title = element_blank(), 
        legend.key =element_blank(), panel.background = element_blank(), 
        panel.grid.minor = element_line(colour = "gray90"), 
        panel.grid.major = element_line(colour = "gray90"))

ggplotly(g1_capitais)%>% 
  layout(annotations = 
           list(x = 1, y = -0.08, text = "Dados:SES. Disponibilizado: https://data.brasil.io/. Elaborado: Vinicius Godinho.", 
                showarrow = F, xref='paper', yref='paper', 
                xanchor='right', yanchor='auto', xshift=0, yshift=0,
                font=list(size=8))
  )
  
  
```

### Média Móvel 7 dias: Novos Óbitos

```{r}


g2_capitais <- ggplot(dados_capitais, aes(date, ma7_deaths, colour = city)) +geom_line(size=.8)  +
  xlab("Data") +
  ylab("") +
  scale_x_date(date_labels = "%d/%m")+
  theme(text = element_text(size=8) ,
        axis.text.x = element_text(angle = 45), 
        axis.title.x = element_text(size=8), 
        legend.text = element_text(size=5,hjust = 0) ,
        legend.position = "bottom",legend.title = element_blank(), 
        legend.key =element_blank(), panel.background = element_blank(), 
        panel.grid.minor = element_line(colour = "gray90"), 
        panel.grid.major = element_line(colour = "gray90"))



ggplotly(g2_capitais)%>% 
  layout(annotations = 
           list(x = 1, y = -0.08, text = "Dados:SES. Disponibilizado: https://data.brasil.io/. Elaborado: Vinicius Godinho.", 
                showarrow = F, xref='paper', yref='paper', 
                xanchor='right', yanchor='auto', xshift=0, yshift=0,
                font=list(size=8))
  )
  
```

